import { Link } from 'react-router-dom';

/**
 * Home – landing page for PiattoRicco ("Digital Kitchen").
 *
 * Layout (top to bottom, easy to explain in class):
 *   1. Hero — cookbook "chapter opener" (centred column, terracotta + sage CTAs)
 *   2. Editorial band — one short mission statement on a muted cream strip
 *   3. Features — three cards from a JavaScript array + .map()
 *   4. Bottom CTA — shown only to guests (conditional && rendering)
 *
 * Styling: Bootstrap utilities + named classes in custom.css (no neon gradients).
 */
function Home() {
  // Same auth check as App.jsx — reads JWT from localStorage (no extra state library)
  const isAuthenticated = !!localStorage.getItem('token');

  // Feature cards data — keeping content in an array teaches list rendering with .map()
  const features = [
    {
      icon: '🍽️',
      title: 'AI Meal Suggestions',
      description:
        'Get personalised daily meal ideas generated by AI, tailored to your calorie goal and preferred cuisines.',
      link: '/dashboard',
      linkLabel: 'Open Dashboard',
    },
    {
      icon: '📅',
      title: 'Weekly Meal Planner',
      description:
        'Plan your entire week at a glance. Assign breakfast, lunch and dinner for each day and keep your diet on track.',
      link: '/planner',
      linkLabel: 'Open Planner',
    },
    {
      icon: '🥦',
      title: 'Smart Pantry',
      description:
        'Track the ingredients you have at home. The AI uses your pantry list when suggesting meals so nothing goes to waste.',
      link: '/pantry',
      linkLabel: 'Open Pantry',
    },
  ];

  return (
    <div>

      {/* ── 1. HERO — chapter opener ─────────────────────────────────────────── */}
      {/*
        .home-hero sets flat cream background (custom.css) — warmth from colour, not gradients.
        Bootstrap grid caps line length like a cookbook column: col-lg-10 (wider on large screens).
      */}
      <section className="home-hero d-flex align-items-center justify-content-center text-center py-5">
        <div className="container px-3 px-md-4">
          <div className="row justify-content-center">
            <div className="col-12 col-lg-10">
              {/* Sage badge mimics a cookbook section label ("Introduction") */}
              <span className="badge badge-sage rounded-pill mb-4 px-3 py-2 fs-6 fw-normal">
                Your digital kitchen
              </span>

              {/* Serif headline from global h1 rule in custom.css */}
              <h1 className="display-4 fw-bold mb-3">
                Your week, planned like a{' '}
                <span className="text-primary">menu</span>
              </h1>

              <p className="lead text-muted mb-5">
                Plan meals around what is in your pantry, map your week at a glance,
                and let AI suggest dishes that fit your goals.
              </p>

              <div className="d-flex flex-wrap gap-3 justify-content-center">
                {!isAuthenticated && (
                  <Link
                    to="/register"
                    className="btn btn-primary btn-lg px-4"
                    id="hero-get-started-btn"
                  >
                    Start your kitchen journal
                  </Link>
                )}
                <Link
                  to="/dashboard"
                  className="btn btn-outline-secondary btn-lg px-4"
                  id="hero-dashboard-btn"
                >
                  Go to Dashboard
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── 2. EDITORIAL BAND — short mission strip ──────────────────────────── */}
      <section className="home-editorial-band py-5">
        <div className="container px-3 px-md-4">
          <div className="row justify-content-center text-center">
            <div className="col-12 col-lg-10">
              <h2 className="fw-bold mb-3">Cook smarter, waste less</h2>
              <p className="text-muted mb-0">
                PiattoRicco connects your pantry, weekly planner, and AI suggestions
                so every meal feels intentional — like following a well-edited recipe book.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ── 3. FEATURES — three recipe-style cards ───────────────────────────── */}
      {/*
        Responsive grid: 1 col mobile → 2 cols tablet → 3 cols desktop.
        .hover-card adds a gentle lift on hover (transform in custom.css).
      */}
      <section className="py-5" id="features">
        <div className="container px-3 px-md-4">
          <div className="text-center mb-5">
            <h2 className="fw-bold">Three tools, one kitchen</h2>
            <p className="text-muted">Everything you need to plan, cook, and shop with less stress.</p>
          </div>

          <div className="row g-4">
            {features.map((feature) => (
              <div key={feature.title} className="col-12 col-md-6 col-lg-4">
                <div className="card h-100 hover-card border-0 shadow-sm p-4">
                  <div className="fs-1 mb-3">{feature.icon}</div>
                  <h5 className="fw-bold mb-2">{feature.title}</h5>
                  <p className="text-muted flex-grow-1">{feature.description}</p>
                  <Link
                    to={feature.link}
                    className="btn btn-outline-primary btn-sm mt-3 align-self-start"
                    id={`feature-link-${feature.title.toLowerCase().replace(/\s+/g, '-')}`}
                  >
                    {feature.linkLabel} →
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── 4. BOTTOM CTA — guests only ────────────────────────────────────── */}
      {!isAuthenticated && (
        <section className="py-5">
          <div className="container px-3 px-md-4">
            <div className="home-cta-box rounded-4 p-5 text-center">
              <div className="fs-1 mb-3">🍽️</div>
              <h3 className="fw-bold mb-3">Reserve your seat at the table</h3>
              <p className="text-muted mb-4">
                Create a free account in seconds and let the AI handle your meal planning.
              </p>
              <Link to="/register" className="btn btn-primary btn-lg px-5" id="bottom-cta-btn">
                Create a free account
              </Link>
            </div>
          </div>
        </section>
      )}

    </div>
  );
}

export default Home;
